# Generated by Django 3.0.1 on 2020-01-06 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solos', '0003_auto_20200102_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='solo',
            name='slug',
            field=models.SlugField(default='sample'),
            preserve_default=False,
        ),
    ]
