# Generated by Django 3.0.1 on 2020-01-07 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solos', '0005_auto_20200107_0329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solo',
            name='album',
        ),
    ]
